let xadado = prompt('isimingizni kiriting')
console.log(`name: ${ xadado }`)
let fayzullayev = prompt('familiyangizni kiriting')
console.log(`family: ${ fayzullayev}`)
let fayzullaye = prompt('yoshingizni kiriting')
console.log(`age: ${ fayzullaye}`)
let fayzullay = prompt('e-mail')
console.log(`e-mail: ${ fayzullay}`)
let fayzulla = prompt('turar joyingiz')
console.log(`accommodation: ${ fayzulla}`)
alert(`Hurmatli ${xadado} bizda mazza qilib baham ko'ring `)